# For more information: https://github.com/elephox-dev/plane
version: '3'
services:
    elephox:
        build:
            context: ./vendor/elephox/plane/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:8000'
        environment:
            WWWUSER: '${WWWUSER}'
            ELEPHOX_PLANE: 1
            XDEBUG_MODE: '${PLANE_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${PLANE_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '${PWD}/:/var/www/html/'
        networks:
            - plane
        depends_on:
            - mailhog
            - postgres
            - redis
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - plane
    postgres:
        image: 'postgres:15'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'plane-postgres:/var/lib/postgresql/data'
        networks:
            - plane
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'plane-redis:/data'
        networks:
            - plane
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
volumes:
    plane-postgres:
        driver: local
    plane-redis:
        driver: local
networks:
    plane:
        driver: bridge
