#!/usr/bin/env php
<?php
declare(strict_types=1);

use Elephox\Builder\Doctrine\AddsDoctrine;
use Elephox\Builder\Whoops\AddsWhoopsHandler;
use Elephox\Console\ConsoleApplicationBuilder;
use Elephox\Web\Routing\Contract\Router;
use Elephox\Web\Routing\RouterBuilder;

require_once 'vendor/autoload.php';
const APP_ROOT = __DIR__;

// Create the custom builder
class ConsoleBuilder extends ConsoleApplicationBuilder {
	use AddsWhoopsHandler;
	use AddsDoctrine;
}

// Build console application
$builder = ConsoleBuilder::create();
$builder->addLogging();
$builder->addWhoops();
$builder->addDoctrine();

// Load app commands
$builder->commands->addNamespace("App\\Commands");

// Add the request router, so we can use it in commands
$builder->services->addSingleton(Router::class, factory: function (): Router {
	$builder = new RouterBuilder();
	$builder->addRoutesFromNamespace("App\\Routes");
	return $builder->build();
});

// Load commands
$builder->commands->addNamespace("Elephox\\Web\\Commands");
$builder->commands->addNamespace("Elephox\\Plane\\Commands");
$builder->commands->addNamespace("Elephox\\Builder\\Doctrine\\Commands");

$app = $builder->build();
$app->run();
